name: SK-MDL
description: A Module core plugin by vSKAH
main: fr.skah.skmdl.api.spigot.ModulesPlugin
author: SKAH#7513
version: 1.1-SNAPSHOT
api-version: 1.16
load: POSTWORLD
softdepend:
  - Jobs
  - Lands
  - NBTAPI
  - Worldguard
  - Vault